#!/usr/bin/env bash
# Собирает prompts/index.yml по frontmatter всех .md в prompts/ и patterns/.
# Использование:
#   ./scripts/build-index.sh                    # пишет в prompts/index.yml
#   ./scripts/build-index.sh /tmp/index.yml     # пишет в указанный путь

set -euo pipefail

REPO_OWNER="Shahimat"
REPO_NAME="ai-prompts"
REPO_BRANCH="main"
RAW_BASE="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/${REPO_BRANCH}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

OUT_FILE="${1:-prompts/index.yml}"

extract_field() {
    local file="$1"
    local field="$2"
    awk -v field="$field" '
        BEGIN { in_fm = 0 }
        /^---$/ {
            if (NR == 1) { in_fm = 1; next }
            if (in_fm) { exit }
            next
        }
        in_fm {
            pattern = "^" field ":[[:space:]]*"
            if (match($0, pattern)) {
                val = substr($0, RSTART + RLENGTH)
                gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
                print val
                exit
            }
        }
    ' "$file"
}

collect() {
    while IFS= read -r file; do
        local rel_path="${file#./}"
        local key kind applicable_to patterns sha256
        key=$(extract_field "$file" "key")
        kind=$(extract_field "$file" "kind")
        applicable_to=$(extract_field "$file" "applicable_to")
        patterns=$(extract_field "$file" "patterns")
        sha256=$(shasum -a 256 "$file" | awk '{print $1}')

        if [[ -z "$key" || -z "$kind" ]]; then
            echo "SKIP (no key/kind): $rel_path" >&2
            continue
        fi

        printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$kind" "$key" "$rel_path" "$sha256" "$applicable_to" "$patterns"
    done
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

find prompts patterns -type f -name "*.md" 2>/dev/null | sort | collect > "$tmp"

emit_group() {
    local group_kind="$1"
    local group_label="$2"
    local any=0
    while IFS=$'\t' read -r kind key path sha256 applicable_to patterns; do
        if [[ "$kind" != "$group_kind" ]]; then continue; fi
        if [[ $any -eq 0 ]]; then
            echo ""
            echo "${group_label}:"
            any=1
        fi
        echo "  - key: $key"
        echo "    path: $path"
        echo "    raw: $RAW_BASE/$path"
        echo "    sha256: $sha256"
        if [[ -n "$patterns" && "$patterns" != "[]" ]]; then
            echo "    patterns: $patterns"
        fi
        if [[ "$kind" == "module" && -n "$applicable_to" ]]; then
            echo "    applicable_to: $applicable_to"
        fi
    done < "$tmp"
    if [[ $any -eq 0 ]]; then
        echo ""
        echo "${group_label}: []"
    fi
}

{
    echo "# generated by scripts/build-index.sh — do not edit manually"
    echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    emit_group "contract" "contracts"
    emit_group "pattern"  "patterns"
    emit_group "module"   "modules"
    emit_group "prompt"   "prompts"
} > "$OUT_FILE"

echo "wrote $OUT_FILE ($(wc -l < "$OUT_FILE" | tr -d ' ') lines)" >&2
